on:
  push:
    branches:
      - dev

jobs:
  test-publish-docker:
    runs-on: ubuntu-latest
    name: Publish quartet-studio to aliyun oss.
    steps:
      - name: Configure environment
        id: config
        run: |
          VERSION=$(echo $GITHUB_REF | sed -e "s/^refs\/tags\/v//")
          echo ::set-output name=version::$VERSION

      - name: Fetch repository
        uses: actions/checkout@master

      - name: Install dependences
        uses: borales/actions-yarn@v2.1.0
        with:
          cmd: install

      - name: Build project
        uses: borales/actions-yarn@v2.1.0
        with:
          cmd: build

      - name: Publish quartet-studio to aliyun oss
        id: ossutil
        uses: go-choppy/ossutil-github-action@master
        with:
          ossArgs: 'cp -r -u ./dist/ oss://test-chinese-quartet-frontend/'
          accessKey: ${{ secrets.ALIYUN_ACCESS_KEY }}
          accessSecret: ${{ secrets.ALIYUN_ACCESS_SECRET }}
          endpoint: oss-ap-southeast-1.aliyuncs.com

      - name: Output command
        run: |
          echo "${{ steps.ossutil.outputs.command }}"
          echo "Publish Quartet Studio ${{ steps.config.outputs.version }} Successfully."

      - name: Dingtalk Robot Message
        uses: leafney/dingtalk-action@v1
        env:
          DINGTALK_ACCESS_TOKEN: ${{ secrets.DINGTALK_ACCESS_TOKEN }}
          DINGTALK_SECRET: ${{ secrets.DINGTALK_SECRET }}
        with:
          msgtype: markdown
          notify_when: 'success'
          title: 发布成功
          text: |
            **<font color=#00FF00 size=4>发布成功</font>**

            ### Quartet Data Portal ${{ steps.config.outputs.version }} 已更新
            > 可通过 http://dev.chinese-quartet.org 链接访问
          at: yjcyxky